export const helpData = {
  DEFAULT: [
    "Was ist die PUNTO 4?",
    "Die PUNTO 4 ist eine zentrale Steuereinheit, die zur Steuerung verschiedener Kanäle und Signale wie Kirchenglocken, Melodien oder Turmuhren dient. Sie ermöglicht sowohl die automatische Ausführung gespeicherter Programme als auch manuelle Befehle über Funktionstasten. Mit bis zu 99 verfügbaren Speicherplätzen bietet sie eine flexible Lösung für komplexe Zeitsteuerungsaufgaben.",
    "Die Programmiermöglichkeiten",
    "Die PUNTO 4 unterscheidet zwischen verschiedenen Programmtypen, um unterschiedlichste zeitliche Anforderungen abzudecken:",
    "Wöchentlich: Dies ist das Standardprogramm für Ereignisse, die sich jede Woche an denselben Tagen und zur selben Uhrzeit wiederholen (z. B. tägliches Läuten).",
    "Periodisch: Erlaubt die Festlegung eines Programms innerhalb eines spezifischen Zeitraums mit Anfangs- und Enddatum (z. B. für eine Festwoche oder eine Saison).",
    "Besondere (Eccezionale): Dient der Programmierung einmaliger Ereignisse an einem ganz speziellen Datum.",
    "Zyklisch: Ermöglicht die Wiederholung eines Signals in regelmäßigen Abständen innerhalb eines definierten Zeitfensters (z. B. alle 30 Minuten zwischen 8:00 und 12:00 Uhr).",
    "Unterdrücken (Unterbindung/Sospensione): Mit dieser Funktion können Sie bestehende automatische Programme für einen bestimmten Zeitraum deaktivieren, ohne sie löschen zu müssen.",
    "Die Untermenüpunkte",
    "Innerhalb dieser Programmtypen können Sie festlegen, was genau gesteuert werden soll:",
    "Glocken (Campane): Steuerung von schwingenden Glocken oder Hämmern mit Angabe der Dauer in Sekunden.",
    "Melodien (Melodie): Auswahl und Abspielen zuvor gespeicherter Melodiefolgen.",
    "Stundenschlagen (Suono Ore): Konfiguration des automatischen Zeitschlags (Stunden-/Viertelstundenschlag).",
    "Dienste (Servizi): Ein universeller Begriff für die Steuerung zusätzlicher elektrischer Geräte oder Hilfskanäle (z. B. Aufzug der Gewichte für die Uhr).",
    "Unterschied: Periodisch vs. Zyklisch",
    "Obwohl beide Begriffe eine Wiederholung suggerieren, haben sie unterschiedliche Funktionen:",
    "Periodisch bezieht sich auf den Kalenderzeitraum. Sie legen fest, dass ein Programm z. B. nur vom 1. Dezember bis zum 24. Dezember aktiv ist.",
    "Zyklisch bezieht sich auf die Häufigkeit innerhalb eines Tages. Hier programmieren Sie Intervalle, in denen ein Signal immer wieder kehrt (Wiederholungsrate).",
    "Das grundlegende Programmiermuster",
    "Jede Programmierung in der PUNTO 4 folgt einer logischen Abfolge. Sie werden Schritt für Schritt durch die Eingabe grgeführt:",
    "Funktionswahl: Sie wählen im Hauptmenü unter 'Programmierung' den Punkt 'Eingeben.'",
    "Typenwahl: Entscheidung für einen Modus (z. B. Wöchentlich oder Periodisch).",
    "Aktionswahl: Auswahl des Kanals (z. B. Glocke 1 oder Melodie 2).",
    "Parameter festlegen:",
    "Dauer: Wie lange soll das Signal aktiv sein (in Sekunden oder über eine Endzeit)?",
    "Zeit: Festlegung der Anfangsstunde (und ggf. Endestunde).",
    "Datum/Tage: Bei periodischen Programmen das Start-/Enddatum; bei wöchentlichen die Wochentage (1=Mo bis 7=So, 0=Alle).",
    "Bestätigung: Abschluss mit der Eingabetaste (Enter), woraufhin das Gerät automatisch den nächsten freien Speicherplatz (z. B. P2 oder W2) vorschlägt.",
    "Die Steuerung der Punto 4 erfolgt über ein übersichtliches Tastenfeld, das sowohl für die Programmierung als auch für den manuellen Betrieb ausgelegt ist.",
    "Tastenfunktionen und Navigation",
    "Die Navigation durch die Menüs der Punto 4 basiert auf einer logischen Struktur aus Eingabe, Bestätigung und Korrektur:",
    "Dateneingabe: Die Zifferntasten '1-0' dienen zur Eingabe von Uhrzeiten, Daten, Wochentagen und Kanalnummern.",
    "Menüführung: Mit den Tasten '+ / -' blättern Sie nacheinander durch die verschiedenen Bildschirminhalte und Menüpunkte.",
    "Bestätigung und Abbruch: Die Eingabetaste (Enter-Symbol) bestätigt Ihre Auswahl oder Daten. Mit 'ESC' verlassen Sie das aktuelle Programmierbild oder kehren im Menü zurück.",
    "Korrektur: Die Pfeiltaste ('←') löscht fehlerhaft eingegebene Daten.",
    "Betriebssteuerung: Die 'STOP'-Taste unterbricht ein laufendes Programm sofort. Für den direkten manuellen Zugriff auf Kanäle (z. B. eine Glocke sofort läuten lassen) werden die entsprechenden Kanaltasten genutzt, wobei eine LED den Status (ON/OFF) anzeigt.",
    "Hilfe: Die 'HELP'-Taste bietet während der Programmierung unterstützende Informationen.",
  ],
  W_GLOCKEN: [
    "Den Code „123“ eingeben und die Eingabetaste ⏎ drücken, bevor mit der Arbeit an den Programmen begonnen wird.",
    "Aus dem Hauptmenü „PROGRAMMIERUNG“ wählen und Eingabetaste ⏎ drücken, um zu bestätigen.",
    "„EINGEBEN“ über die Tasten „+“ und „-“ wählen und Eingabetaste ⏎ drücken, um zu bestätigen.",
    "„WOECHENTLICHE“ über die Tasten „+“ und „-“ wählen und Eingabetaste ⏎ drücken, um zu bestätigen.",
    "„GLOCKEN“ über die Tasten „+“ und „-“ wählen und Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Von 1 bis 2 wählen, wenn 2 Glocken gespeichert sind oder von 1 bis 4, wenn 3 oder 4 Glocken programmiert sind; Eingabetaste ⏎ drücken, um zu bestätigen (wenn mehr Glocken gewählt werden sollen, nicht das Zeichen „+“ zwischen die einzelnen Glocken setzen).",
    "Die Dauer (bis zu 99 Sekunden) eingeben; wenn eine Dauer von mehr als 99 Sek. gewünscht wird, „0“ eintasten und die Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Die Anfangsstunde eintasten (Stunden und Minuten) und die Eingabetaste ⏎ drücken, um zu bestätigen. Wenn eine längere Dauer gewählt wird, die Endestunde eingeben und die Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Tage (1=Montag, 7=Sonntag u.s.w.) eingeben - „0“, wenn alle Tage eingesetzt werden sollen - und Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Es handelt sich hier um das PROGRAMMIERUNG Nr. ...; es können 99 Programmierungen vorgenommen werden;für den Aussprung „ESC“ „ESC“ drücken.",
    "„2“ eintasten und Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Eingabetaste ⏎ drücken, um zu bestätigen.",
    "Mit der Taste „+“ kann man, durch jeweils einen Tastendruck, zum naechsten Programm überspringen; und auf die gleiche Weise geht man mit der Taste „-“ zum vorhergehenden Programm zurück.",
    "Eingabetaste ⏎ drücken, um die Endestunde abzulesen.",
    "Am Schluss des Programmierens mehrere Male „ESC“ drücken, um auszuspringen und zum Hauptmenü zurückzukehren",
  ],
  EDIT_MELODY_NAMES: [
    "Wählen Sie eine Melodie 1-8.",
    "Nutzen Sie +/- zum Ändern der Buchstaben.",
    "Zahlen können direkt getippt werden.",
  ],
};
